import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import API from "../services/api";

const PublicReportPage = () => {
  const { id } = useParams(); // Get :id from the URL
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAudit = async () => {
      try {
        const response = await API.get(`/audits/${id}`);
        setData(response.data);
      } catch (error) {
        console.error("Error fetching audit:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchAudit();
  }, [id]);

  if (loading)
    return (
      <div className="text-white text-center py-20">Loading Report...</div>
    );
  if (!data)
    return <div className="text-white text-center py-20">Report Not Found</div>;

  return (
    <div className="min-h-screen bg-slate-950 text-white px-6 py-12">
      <div className="max-w-4xl mx-auto">
        <header className="text-center mb-16">
          <h1 className="text-5xl font-black mb-4">Savings Report</h1>
          <p className="text-slate-400 text-xl">
            Audit for {data.companyName || "Your Organization"}
          </p>
        </header>

        {/* Savings Overview */}
        <div className="grid md:grid-cols-2 gap-8 mb-12">
          <div className="bg-blue-600/10 border border-blue-500/50 p-8 rounded-[2rem]">
            <p className="text-sm font-bold text-blue-400 uppercase">
              Monthly Savings
            </p>
            <h2 className="text-6xl font-black">${data.monthlySavings}</h2>
          </div>
          <div className="bg-slate-900 border border-slate-800 p-8 rounded-[2rem]">
            <p className="text-sm font-bold text-green-400 uppercase">
              Annualized
            </p>
            <h2 className="text-6xl font-black">${data.annualSavings}</h2>
          </div>
        </div>

        {/* Recommendations List */}
        <div className="space-y-4">
          <h3 className="text-sm font-bold uppercase text-slate-500 px-4">
            Detailed Recommendations
          </h3>
          {data.recommendations?.map((item, index) => (
            <div
              key={index}
              className="bg-slate-900/40 border border-slate-800 rounded-3xl p-6"
            >
              <div className="flex justify-between items-center">
                <div>
                  <h4 className="text-2xl font-bold">{item.tool}</h4>
                  <p className="text-slate-400">
                    {item.currentPlan} →{" "}
                    <span className="text-blue-400">
                      {item.recommendedPlan}
                    </span>
                  </p>
                </div>
                <div className="text-right text-green-400 text-2xl font-black">
                  +${item.savings}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer instead of Lead Gate */}
        <footer className="mt-20 pt-10 border-t border-slate-800 text-center text-slate-500">
          <p>
            Generated by SpendPilot AI. Want a new audit?{" "}
            <a href="/" className="text-blue-500 underline">
              Click here
            </a>
          </p>
        </footer>
      </div>
    </div>
  );
};

export default PublicReportPage;
